/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Aeon SaaS Starter Kit
 * Aeon SaaS Starter Kit API
 * OpenAPI spec version: 1.0.0
 */
/**
 * User role in the system
 */
export type UserDtoRole = typeof UserDtoRole[keyof typeof UserDtoRole];


export const UserDtoRole = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  GUEST: 'GUEST',
} as const;

export interface UserDto {
  /** User email address */
  email: string;
  /** Clerk user ID for authentication */
  clerkId: string;
  /** User display name */
  name?: string;
  /** User role in the system */
  role?: UserDtoRole;
}

export type UserResponseDtoName = { [key: string]: unknown };

export type UserResponseDtoRole = typeof UserResponseDtoRole[keyof typeof UserResponseDtoRole];


export const UserResponseDtoRole = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  GUEST: 'GUEST',
} as const;

export interface UserResponseDto {
  id: string;
  email: string;
  clerkId: string;
  name?: UserResponseDtoName;
  role: UserResponseDtoRole;
}

